import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { colors } from '../constants/theme';
import { Button, Card, Input } from '../components/UI';
import { register } from '../services/authService';
import type { UserRole } from '../types/auth';
const roles:UserRole[]=['PATIENT','DOCTOR','NURSE','PHARMACIST'];
export default function Signup(){const router=useRouter();const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<UserRole>('PATIENT');const [loading,setLoading]=useState(false);const submit=async()=>{if(name.length<2||!email||password.length<8)return Alert.alert('Lengkapi data','Nama minimal 2 karakter, email valid, password minimal 8 karakter.');setLoading(true);try{const r=await register(name,email,password,role);Alert.alert('Berhasil',r.message,[{text:'Login',onPress:()=>router.replace('/login')}]);}catch(e:any){Alert.alert('Registrasi gagal',e?.response?.data?.message||'Tidak dapat membuat akun.');}finally{setLoading(false);}};return <KeyboardAvoidingView style={s.root} behavior={Platform.OS==='ios'?'padding':undefined}><Card><Text style={s.title}>Create account</Text><Text style={s.sub}>Create your AssistDoc clinic account.</Text><Input label="Full name" value={name} onChangeText={setName} placeholder="Nama lengkap"/><Input label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Input label="Password" value={password} onChangeText={setPassword} secureTextEntry/><Text style={s.label}>Role</Text><View style={s.roles}>{roles.map(r=><Pressable key={r} onPress={()=>setRole(r)} style={[s.role,role===r&&s.active]}><Text style={[s.roleText,role===r&&s.activeText]}>{r}</Text></Pressable>)}</View><Button title="Create account" onPress={submit} loading={loading}/><Pressable onPress={()=>router.replace('/login')}><Text style={s.back}>Already have an account? <Text style={{color:colors.tealBright,fontWeight:'900'}}>Login</Text></Text></Pressable></Card></KeyboardAvoidingView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.cream,padding:16,justifyContent:'center'},title:{fontSize:26,fontWeight:'900',color:colors.navyDark},sub:{color:colors.muted,marginTop:4,marginBottom:20},label:{color:colors.navyDark,fontSize:11,fontWeight:'900',marginBottom:7},roles:{flexDirection:'row',flexWrap:'wrap',gap:7},role:{borderWidth:1,borderColor:colors.border,borderRadius:11,paddingHorizontal:11,paddingVertical:9},active:{backgroundColor:'#E7F2F3',borderColor:colors.tealBright},roleText:{fontSize:10,color:colors.muted,fontWeight:'900'},activeText:{color:colors.tealBright},back:{textAlign:'center',marginTop:15,color:colors.muted,fontSize:12}});
