import type { UserRole } from '../types/auth';
export type MenuItem = { key: string; label: string; icon: string; description: string };
const m = (key: string, label: string, icon: string, description: string): MenuItem => ({ key, label, icon, description });
export const roleMenus: Record<UserRole, MenuItem[]> = {
  ADMIN: [m('dashboard','Dashboard','grid-outline','Today overview'),m('patients','Patients','people-outline','Patient records'),m('registration','Registration','person-add-outline','Register and check-in'),m('queue','Queue','time-outline','Live outpatient queue'),m('invoices','Invoices & Payments','receipt-outline','Billing and payments'),m('reports','Reports','bar-chart-outline','Visits and revenue'),m('users','User Management','people-circle-outline','Clinic accounts'),m('settings','Settings','settings-outline','Connection and app settings')],
  DOCTOR: [m('dashboard','Dashboard','grid-outline','Clinical overview'),m('queue','Patient Queue','time-outline','Patients ready for consultation'),m('patients','Patient Info','people-outline','Patient records'),m('consultation','Consultation','medkit-outline','Consultation workspace'),m('diagnosis','Diagnosis','clipboard-outline','Clinical diagnosis'),m('prescriptions','Prescriptions','flask-outline','Create prescriptions'),m('notes','Medical Notes','document-text-outline','Clinical notes'),m('schedule','Schedule','calendar-outline','Today schedule')],
  NURSE: [m('dashboard','Dashboard','grid-outline','Nursing overview'),m('queue','Patient Queue','time-outline','Waiting patients'),m('search','Patient Search','search-outline','Find patients'),m('patient','Patient Info & Vitals','person-outline','Selected patient'),m('assessment','Initial Assessment','clipboard-outline','Initial assessment'),m('vitals','Record Vitals','pulse-outline','Vital signs'),m('notes','Notes & Tasks','create-outline','Nursing notes'),m('schedule','Schedule','calendar-outline','Today schedule')],
  PHARMACIST: [m('dashboard','Dashboard','grid-outline','Pharmacy overview'),m('queue','Prescription Queue','time-outline','Incoming prescriptions'),m('inventory','Medicine Inventory','cube-outline','Medicine inventory'),m('prescriptions','Prescription Detail','flask-outline','Prescription details'),m('stock','Stock Management','layers-outline','Stock monitoring'),m('notifications','Notifications','notifications-outline','Pharmacy alerts'),m('reports','Reports & Analytics','bar-chart-outline','Pharmacy analytics'),m('schedule','Schedule','calendar-outline','Today schedule')],
  PATIENT: [m('dashboard','Dashboard','grid-outline','Your clinic overview'),m('queue','My Queue','time-outline','Current queue'),m('history','Visit History','document-text-outline','Visit records'),m('invoices','Invoices','receipt-outline','Payment status'),m('schedule','Schedule','calendar-outline','Your schedule')],
};
export const roleLabels: Record<UserRole,string> = { ADMIN:'Administrator', DOCTOR:'Doctor', NURSE:'Nurse', PHARMACIST:'Pharmacist', PATIENT:'Patient' };
