import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import Screen from './Screen';
import { Badge, Button, Card, Input, Section, styles as ui } from './UI';
import { colors } from '../constants/theme';
import { roleLabels } from '../constants/navigation';
import type { UserRole } from '../types/auth';
import { useAuth } from '../context/AuthContext';
import { getAdminDashboard } from '../services/adminService';
import { API_URL, checkServer } from '../services/api';
import { clinic, unwrap } from '../services/clinicService';

const money = (n: any) => new Intl.NumberFormat('id-ID', { style:'currency', currency:'IDR', maximumFractionDigits:0 }).format(Number(n || 0));
const statusTone = (status?: string): 'info'|'success'|'warning'|'danger' => status === 'WAITING' || status === 'PENDING' || status === 'UNPAID' ? 'warning' : status === 'COMPLETED' || status === 'PAID' || status === 'READY' ? 'success' : 'info';
const statusLabel = (x?: string) => String(x || '—').replaceAll('_',' ');
const errMsg = (e:any) => e?.response?.data?.message || e?.message || 'Operation failed.';

function Empty({text='No data available.'}:{text?:string}) { return <Card><View style={s.empty}><Ionicons name="file-tray-outline" size={27} color={colors.muted}/><Text style={s.muted}>{text}</Text></View></Card>; }
function Stat({label,value,icon,tone='teal'}:{label:string;value:any;icon:string;tone?:'teal'|'amber'|'green'|'violet'}) { const bg=tone==='amber'?'#FFF3DD':tone==='green'?'#E8F5EF':tone==='violet'?'#EEEAF8':'#E8F2F6'; const fg=tone==='amber'?colors.warning:tone==='green'?colors.success:tone==='violet'?colors.violet:colors.tealBright; return <Card><View style={[s.statIcon,{backgroundColor:bg}]}><Ionicons name={icon as any} size={19} color={fg}/></View><Text style={s.statValue}>{value}</Text><Text style={s.muted}>{label}</Text></Card>; }
function Row({icon='document-text-outline',title,subtitle,right,onPress}:{icon?:string;title:string;subtitle?:string;right?:React.ReactNode;onPress?:()=>void}) { const C=onPress?Pressable:View; return <C {...(onPress?{onPress}: {})} style={s.row}><View style={s.rowIcon}><Ionicons name={icon as any} size={18} color={colors.tealBright}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text>{subtitle&&<Text style={s.rowSub}>{subtitle}</Text>}</View>{right}</C>; }

export default function RoleScreen({screen}:{screen:string}) { const {user}=useAuth(); const role=user!.role; const common={role,screen}; switch(screen){
  case 'dashboard': return <Dashboard {...common}/>;
  case 'patients': return <Patients {...common}/>;
  case 'registration': return <Registration {...common}/>;
  case 'queue': return <Queue {...common}/>;
  case 'invoices': return <Invoices {...common}/>;
  case 'reports': return <Reports {...common}/>;
  case 'users': return <Users {...common}/>;
  case 'settings': return <Settings {...common}/>;
  case 'consultation': return <Consultation {...common}/>;
  case 'diagnosis': return <Diagnosis {...common}/>;
  case 'prescriptions': return <Prescriptions {...common}/>;
  case 'notes': return <Notes {...common}/>;
  case 'schedule': return <Schedule {...common}/>;
  case 'search': return <SearchPatients {...common}/>;
  case 'patient': return <PatientInfo {...common}/>;
  case 'assessment': return <Assessment {...common}/>;
  case 'vitals': return <Vitals {...common}/>;
  case 'inventory': return <Inventory {...common}/>;
  case 'stock': return <Stock {...common}/>;
  case 'notifications': return <Notifications {...common}/>;
  case 'history': return <History {...common}/>;
  default: return <Dashboard {...common}/>;
} }

type P={role:UserRole;screen:string};

function Dashboard({role}:P){ const [rows,setRows]=useState<any[]>([]); const [admin,setAdmin]=useState<any>(null); const [loading,setLoading]=useState(true); const load=useCallback(async()=>{setLoading(true);try{if(role==='ADMIN')setAdmin((await getAdminDashboard()).data);else setRows(unwrap(await clinic.visits())||[]);}catch(e){}finally{setLoading(false);}},[role]);useEffect(()=>{load();},[load]);
  const d=admin||{}; const waiting=admin?.waiting ?? rows.filter(v=>v.status==='WAITING').length; const completed=admin?.completed ?? rows.filter(v=>v.status==='COMPLETED'||v.status==='PAID').length; const consult=admin?.inConsultation ?? rows.filter(v=>v.status==='IN_CONSULTATION').length;
  return <Screen title={`${roleLabels[role]} Dashboard`} subtitle={role==='ADMIN'?"Today's overview, queue and payment operations.":role==='DOCTOR'?"Today's queue, patient information and consultation workspace.":role==='NURSE'?"Patient queue, initial assessment and vital signs.":role==='PHARMACIST'?"Prescription queue, medicine inventory and preparation.":"Track your queue, visit history and payment status."} onRefresh={load}>
    <Card dark><Text style={s.darkKicker}>CLINIC OUTPATIENT MANAGEMENT</Text><Text style={s.darkTitle}>Good day, {userName(role)}</Text><Text style={s.darkText}>AssistDoc keeps registration, queue, clinical care, pharmacy and payment in one mobile workspace.</Text></Card>
    <View style={s.grid}><Stat label={role==='ADMIN'?'Patients Today':'Visits'} value={admin?.todayVisits ?? rows.length} icon="people-outline"/><Stat label="Waiting" value={waiting} icon="time-outline" tone="amber"/><Stat label="Consultation" value={consult} icon="medkit-outline"/><Stat label="Completed" value={completed} icon="checkmark-circle-outline" tone="green"/></View>
    {role==='ADMIN'&&<Card><Section title="Revenue Summary" subtitle="Today's payment operations"/><Text style={s.bigMoney}>{money(d.todayRevenue)}</Text><View style={s.two}><View><Text style={s.muted}>Unpaid invoices</Text><Text style={s.smallBig}>{d.unpaidInvoices||0}</Text></View><View><Text style={s.muted}>Paid invoices</Text><Text style={s.smallBig}>{d.paid||0}</Text></View></View></Card>}
    <Card><Section title="Today's Queue" subtitle="Patient status across the outpatient flow"/>{(admin?.queue||rows).slice(0,6).map((v:any)=><Row key={v.id} icon="person-outline" title={v.patient?.name||`Visit #${v.id}`} subtitle={`${v.doctor?.name||'Doctor'} • ${dateTime(v.visitDate)}`} right={<Badge tone={statusTone(v.status)}>{statusLabel(v.status)}</Badge>}/>)}{!(admin?.queue||rows).length&&<Text style={s.muted}>No visits today.</Text>}</Card>
  </Screen> }
function userName(role:string){ return role==='ADMIN'?'Main Admin':role==='DOCTOR'?'Doctor':role==='NURSE'?'Nurse':role==='PHARMACIST'?'Pharmacist':'Patient'; }

function Patients({role}:P){ const [q,setQ]=useState('');const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(false);const [form,setForm]=useState({name:'',gender:'Male',age:'',phone:'',address:''});const load=useCallback(async()=>{setLoading(true);try{setRows(unwrap(await clinic.patients(q))||[]);}catch(e){Alert.alert('Patients',errMsg(e));}finally{setLoading(false);}},[q]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[load]);const create=async()=>{try{const r=await clinic.createPatient({...form,age:Number(form.age)});Alert.alert('Success','Patient created successfully.');setForm({name:'',gender:'Male',age:'',phone:'',address:''});setRows(x=>[unwrap(r),...x]);}catch(e){Alert.alert('Create patient',errMsg(e));}};return <Screen title="Patients" subtitle={role==='ADMIN'?'Search and manage registered patient records.':'Quick access to patient records.'} onRefresh={load}><Input label="Search patient" value={q} onChangeText={setQ} placeholder="Name or phone" autoCapitalize="none"/><Card><Section title={`${rows.length} Patient Records`} subtitle={loading?'Loading...':'Tap a patient to review basic information.'}/>{rows.map(p=><Row key={p.id} icon="person-circle-outline" title={p.name} subtitle={`${p.gender} • ${p.age} years • ${p.phone}`} right={<Text style={s.chev}>›</Text>}/>)}</Card>{role==='ADMIN'&&<Card><Section title="Quick Add Patient" subtitle="Same validation as the existing client/server."/><Input label="Name" value={form.name} onChangeText={v=>setForm({...form,name:v})} placeholder="Full name"/><View style={s.formRow}><View style={{flex:1}}><Input label="Age" value={form.age} onChangeText={v=>setForm({...form,age:v})} keyboardType="numeric" placeholder="28"/></View><View style={{flex:1}}><Input label="Gender" value={form.gender} onChangeText={v=>setForm({...form,gender:v})} placeholder="Male/Female"/></View></View><Input label="Phone" value={form.phone} onChangeText={v=>setForm({...form,phone:v})} keyboardType="phone-pad"/><Input label="Address" value={form.address} onChangeText={v=>setForm({...form,address:v})} placeholder="Address"/><Button title="Create patient" onPress={create}/></Card>}</Screen> }

function Registration({role}:P){const [patients,setPatients]=useState<any[]>([]);const [doctors,setDoctors]=useState<any[]>([]);const [existing,setExisting]=useState('');const [doctorId,setDoctorId]=useState('');const [form,setForm]=useState({name:'',gender:'Male',age:'',phone:'',address:'',complaint:''});const load=useCallback(async()=>{try{const [p,d]=await Promise.all([clinic.patients(),clinic.doctors()]);setPatients(unwrap(p)||[]);setDoctors(unwrap(d)||[]);if(!doctorId&&unwrap(d)?.[0])setDoctorId(String(unwrap(d)[0].id));}catch(e){Alert.alert('Registration',errMsg(e));}},[doctorId]);useEffect(()=>{load();},[load]);const submit=async()=>{try{let pid=Number(existing);if(!pid){const p=await clinic.createPatient({...form,age:Number(form.age)});pid=Number(unwrap(p).id);}await clinic.createVisit({patientId:pid,doctorId:Number(doctorId),complaint:form.complaint});Alert.alert('Registration complete','Patient has been added to the waiting queue.');setExisting('');setForm({name:'',gender:'Male',age:'',phone:'',address:'',complaint:''});}catch(e){Alert.alert('Registration failed',errMsg(e));}};return <Screen title="New Registration" subtitle="Existing patient or create a new patient, then check-in to queue." onRefresh={load}><Card><Section title="Patient" subtitle="Choose an existing record or create a new one."/><Text style={s.label}>Existing Patient</Text><View style={s.chips}><Pressable onPress={()=>setExisting('')} style={[s.chip,!existing&&s.chipActive]}><Text style={[s.chipText,!existing&&s.chipTextActive]}>New Patient</Text></Pressable>{patients.slice(0,12).map(p=><Pressable key={p.id} onPress={()=>setExisting(String(p.id))} style={[s.chip,existing===String(p.id)&&s.chipActive]}><Text style={[s.chipText,existing===String(p.id)&&s.chipTextActive]}>{p.name}</Text></Pressable>)}</View>{!existing&&<><Input label="Name" value={form.name} onChangeText={v=>setForm({...form,name:v})}/><View style={s.formRow}><View style={{flex:1}}><Input label="Age" value={form.age} onChangeText={v=>setForm({...form,age:v})} keyboardType="numeric"/></View><View style={{flex:1}}><Input label="Gender" value={form.gender} onChangeText={v=>setForm({...form,gender:v})}/></View></View><Input label="Phone" value={form.phone} onChangeText={v=>setForm({...form,phone:v})} keyboardType="phone-pad"/><Input label="Address" value={form.address} onChangeText={v=>setForm({...form,address:v})}/></>}<Text style={s.label}>Doctor</Text><View style={s.chips}>{doctors.map(d=><Pressable key={d.id} onPress={()=>setDoctorId(String(d.id))} style={[s.chip,doctorId===String(d.id)&&s.chipActive]}><Text style={[s.chipText,doctorId===String(d.id)&&s.chipTextActive]}>{d.name}</Text></Pressable>)}</View><Input label="Initial complaint" value={form.complaint} onChangeText={v=>setForm({...form,complaint:v})} multiline placeholder="Main complaint..."/><Button title="Check-in to Queue" onPress={submit}/></Card></Screen>}

function Queue({role}:P){const [rows,setRows]=useState<any[]>([]);const load=useCallback(async()=>{try{setRows(unwrap(await clinic.visits())||[]);}catch(e){Alert.alert('Queue',errMsg(e));}},[]);useEffect(()=>{load();},[load]);const grouped=['WAITING','IN_CONSULTATION','COMPLETED','PAID'];const update=async(id:number,status:string)=>{try{await clinic.status(id,status);await load();}catch(e){Alert.alert('Queue action',errMsg(e));}};return <Screen title={role==='PATIENT'?'My Queue':'Patient Queue'} subtitle="Live queue shared across the AssistDoc outpatient workflow." onRefresh={load}>{grouped.map(g=>{const items=rows.filter(v=>v.status===g);return <Card key={g}><View style={s.sectionRow}><Section title={statusLabel(g)}/><Badge tone={statusTone(g)}>{items.length} patients</Badge></View>{items.map(v=><View key={v.id} style={s.queueItem}><View style={{flex:1}}><Text style={s.rowTitle}>{v.patient?.name||`Visit #${v.id}`}</Text><Text style={s.rowSub}>{v.doctor?.name} • {dateTime(v.visitDate)}</Text></View><Badge tone={statusTone(v.status)}>{statusLabel(v.status)}</Badge>{role==='DOCTOR'&&g==='WAITING'&&<Button title="Start" onPress={()=>update(v.id,'IN_CONSULTATION')}/>} {role==='DOCTOR'&&g==='IN_CONSULTATION'&&<Button title="Complete" onPress={()=>update(v.id,'COMPLETED')} secondary/>}{role==='ADMIN'&&g!=='PAID'&&<Pressable onPress={()=>update(v.id,g==='WAITING'?'IN_CONSULTATION':g==='IN_CONSULTATION'?'COMPLETED':'PAID')} style={s.smallAction}><Text style={s.smallActionText}>{g==='WAITING'?'Start':g==='IN_CONSULTATION'?'Complete':'Mark Paid'}</Text></Pressable>}</View>)}{!items.length&&<Text style={s.muted}>No patients.</Text>}</Card>})}</Screen>}

function Invoices({role}:P){
  const [rows,setRows]=useState<any[]>([]); const [method,setMethod]=useState('CASH');
  const load=useCallback(async()=>{try{setRows(unwrap(await clinic.visits())||[]);}catch(e){Alert.alert('Invoices',errMsg(e));}},[]);
  useEffect(()=>{load();},[load]);
  const pay=async(id:number)=>{try{await clinic.pay(id,method);Alert.alert('Payment complete','Invoice paid successfully.');load();}catch(e){Alert.alert('Payment failed',errMsg(e));}};
  const create=async(visitId:number)=>{try{await clinic.createInvoice(visitId);Alert.alert('Invoice','Invoice generated.');load();}catch(e){Alert.alert('Invoice',errMsg(e));}};
  const inv=rows.filter(v=>v.invoice); const completable=rows.filter(v=>!v.invoice&&v.status==='COMPLETED');
  return <Screen title={role==='PATIENT'?'My Invoices':'Invoices & Payments'} subtitle="Review invoice totals and payment status." onRefresh={load}>
    {role==='ADMIN'&&<><Text style={s.label}>Payment Method</Text><View style={s.chips}>{['CASH','TRANSFER','E_WALLET'].map(x=><Pressable key={x} onPress={()=>setMethod(x)} style={[s.chip,method===x&&s.chipActive]}><Text style={[s.chipText,method===x&&s.chipTextActive]}>{x.replace('_',' ')}</Text></Pressable>)}</View></>}
    {inv.map(v=>{const i=v.invoice;return <Card key={i.id}><View style={s.sectionRow}><View style={{flex:1}}><Text style={s.rowTitle}>{`Invoice #${i.id}`}</Text><Text style={s.rowSub}>{v.patient?.name} • {dateTime(v.visitDate)}</Text></View><Badge tone={statusTone(i.status)}>{i.status}</Badge></View><View style={s.moneyGrid}><View><Text style={s.muted}>Subtotal</Text><Text style={s.smallBig}>{money(i.subtotal)}</Text></View><View><Text style={s.muted}>Total</Text><Text style={s.smallBig}>{money(i.total)}</Text></View></View>{i.status==='UNPAID'&&role==='ADMIN'&&<Button title="Confirm Payment" onPress={()=>pay(i.id)}/>}<Button title="View Invoice Detail" onPress={async()=>{try{const r=await clinic.invoice(i.id);const x=unwrap(r);Alert.alert('Invoice Detail',`Invoice #${x.id}\nTotal: ${money(x.total)}\nStatus: ${x.status}`);}catch(e){Alert.alert('Invoice',errMsg(e));}}} secondary/></Card>})}
    {role==='ADMIN'&&completable.map(v=><Card key={`gen-${v.id}`}><Text style={s.rowTitle}>{v.patient?.name} • Visit #{v.id}</Text><Text style={s.rowSub}>Completed visit without invoice.</Text><Button title="Generate Invoice" onPress={()=>create(v.id)}/></Card>)}
    {!inv.length&&!completable.length&&<Empty text="No invoices available yet."/>}
  </Screen>;
}

function Reports({role}:P){const [range,setRange]=useState('weekly');const [d,setD]=useState<any>(null);const load=useCallback(async()=>{try{setD(unwrap(await clinic.reports(range)));}catch(e){Alert.alert('Reports',errMsg(e));}},[range]);useEffect(()=>{if(role==='ADMIN')load();},[load,role]);if(role!=='ADMIN')return <PharmacyReports/>;return <Screen title="Reports & Analytics" subtitle="Daily, weekly and monthly visits and revenue." onRefresh={load}><View style={s.chips}>{['daily','weekly','monthly'].map(x=><Pressable key={x} onPress={()=>setRange(x)} style={[s.chip,range===x&&s.chipActive]}><Text style={[s.chipText,range===x&&s.chipTextActive]}>{x}</Text></Pressable>)}</View><View style={s.grid}><Stat label="Total Visits" value={d?.totalVisits||0} icon="calendar-outline"/><Stat label="Revenue" value={money(d?.totalRevenue)} icon="wallet-outline" tone="green"/></View><Card><Section title="Activity Chart" subtitle="Visits per day"/>{(d?.chart||[]).map((x:any)=><View key={x.date} style={s.chartRow}><Text style={s.chartDate}>{x.date.slice(5)}</Text><View style={s.barTrack}><View style={[s.bar,{width:`${Math.min(100,Math.max(4,(x.visits||0)*12))}%`}]} /></View><Text style={s.chartValue}>{x.visits}</Text></View>)}</Card></Screen>}
function PharmacyReports(){const [vs,setVs]=useState<any[]>([]);const [ms,setMs]=useState<any[]>([]);useEffect(()=>{Promise.all([clinic.visits(),clinic.medicines()]).then(([v,m])=>{setVs(unwrap(v)||[]);setMs(unwrap(m)||[]);}).catch(()=>{});},[]);const rx=vs.flatMap(v=>(v.prescriptions||[]).map((p:any)=>({...p,patient:v.patient})));return <Screen title="Reports & Analytics" subtitle="Medicine usage and pharmacy preparation overview."><View style={s.grid}><Stat label="Prescriptions" value={rx.length} icon="flask-outline"/><Stat label="Low Stock" value={ms.filter(m=>m.stock<20).length} icon="warning-outline" tone="amber"/><Stat label="Ready" value={rx.filter(r=>r.status==='READY').length} icon="checkmark-circle-outline" tone="green"/></View><Card><Section title="Medicine Usage"/>{rx.slice(0,12).map(r=><Row key={r.id} title={r.medicine?.name} subtitle={`${r.patient?.name||'Patient'} • Qty ${r.quantity}`} right={<Badge tone={statusTone(r.status)}>{r.status}</Badge>}/>)}</Card></Screen>}

function Users({role}:P){const [rows,setRows]=useState<any[]>([]);const load=useCallback(async()=>{try{setRows(unwrap(await clinic.users())||[]);}catch(e){Alert.alert('Users',errMsg(e));}},[]);useEffect(()=>{load();},[load]);return <Screen title="User Management" subtitle="Clinic staff accounts and role access." onRefresh={load}><Card>{rows.map(u=><Row key={u.id} icon="person-circle-outline" title={u.name} subtitle={`${u.email} • ${u.role}`} right={<Badge>{u.role}</Badge>}/>)}</Card>{!rows.length&&<Empty/>}</Screen>}
function Settings({role}:P){const [result,setResult]=useState('');const test=async()=>{try{const r=await checkServer();setResult(`Server: ${r.data.server} • Database: ${r.data.database}`);}catch(e:any){setResult(`Connection failed: ${e?.response?.status||'Network Error'}`);}};return <Screen title="Settings" subtitle="Clinic configuration and mobile connection reference."><Card><Section title="Workspace"/><Row title="Role" subtitle={roleLabels[role]}/><Row title="API URL" subtitle={API_URL}/><Row title="Expo" subtitle="SDK 57.0.14"/><Row title="React Native" subtitle="0.86.x"/><Button title="Test server & database" onPress={test}/>{result&&<Text style={[s.result,result.includes('failed')?{color:colors.danger}:{color:colors.success}]}>{result}</Text>}</Card><Card><Section title="Connection Checklist"/><Text style={s.muted}>• Phone and PC use the same Wi-Fi</Text><Text style={s.muted}>• Express listens on 0.0.0.0:3000</Text><Text style={s.muted}>• PostgreSQL is connected</Text><Text style={s.muted}>• .env points to your PC LAN IPv4</Text></Card></Screen>}

function Consultation({role}:P){const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [diag,setDiag]=useState('');const [notes,setNotes]=useState('');const [meds,setMeds]=useState<any[]>([]);const [medId,setMedId]=useState('');const [qty,setQty]=useState('1');const load=useCallback(async()=>{try{const [v,m]=await Promise.all([clinic.visits(),clinic.medicines()]);const data=unwrap(v)||[];setRows(data.filter((x:any)=>x.status==='IN_CONSULTATION'));setMeds(unwrap(m)||[]);}catch(e){Alert.alert('Consultation',errMsg(e));}},[]);useEffect(()=>{load();},[load]);const saveDiagnosis=async()=>{if(!selected||!diag)return Alert.alert('Diagnosis','Select a visit and enter diagnosis.');try{await clinic.diagnosis({visitId:selected.id,diagnosisName:diag,notes});Alert.alert('Saved','Diagnosis saved.');setDiag('');}catch(e){Alert.alert('Diagnosis',errMsg(e));}};const addRx=async()=>{if(!selected||!medId)return Alert.alert('Prescription','Select a medicine.');try{await clinic.prescription({visitId:selected.id,medicineId:Number(medId),quantity:Number(qty)});Alert.alert('Saved','Prescription created.');setMedId('');load();}catch(e){Alert.alert('Prescription',errMsg(e));}};const complete=async()=>{if(!selected)return;try{await clinic.status(selected.id,'COMPLETED');Alert.alert('Completed','Visit completed.');setSelected(null);load();}catch(e){Alert.alert('Complete visit',errMsg(e));}};return <Screen title="Consultation" subtitle="Diagnosis, prescription and medical notes." onRefresh={load}><Card><Section title="Patients In Consultation"/>{rows.map(v=><Pressable key={v.id} onPress={()=>{setSelected(v);setNotes(v.notes||'')}} style={[s.selectRow,selected?.id===v.id&&s.selected]}><View style={{flex:1}}><Text style={s.rowTitle}>{v.patient?.name}</Text><Text style={s.rowSub}>{v.patient?.age} yrs • {v.patient?.gender} • {v.doctor?.name}</Text></View><Badge tone="info">IN CONSULTATION</Badge></Pressable>)}{!rows.length&&<Text style={s.muted}>No patients are currently in consultation.</Text>}</Card>{selected&&<><Card><Section title="Clinical Notes" subtitle={selected.complaint||'No complaint recorded.'}/><Input label="Diagnosis" value={diag} onChangeText={setDiag} placeholder="e.g. Common Cold"/><Input label="Notes" value={notes} onChangeText={setNotes} multiline placeholder="Clinical notes"/><Button title="Save Diagnosis" onPress={saveDiagnosis}/></Card><Card><Section title="Prescription"/><Text style={s.label}>Medicine</Text><View style={s.chips}>{meds.map(m=><Pressable key={m.id} onPress={()=>setMedId(String(m.id))} style={[s.chip,medId===String(m.id)&&s.chipActive]}><Text style={[s.chipText,medId===String(m.id)&&s.chipTextActive]}>{m.name}</Text></Pressable>)}</View><Input label="Quantity" value={qty} onChangeText={setQty} keyboardType="numeric"/><Button title="Add Prescription" onPress={addRx}/><Button title="Complete Consultation" onPress={complete} secondary/></Card></>}</Screen>}

function Diagnosis({role}:P){const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [name,setName]=useState('');const [notes,setNotes]=useState('');const load=useCallback(async()=>{try{setRows((unwrap(await clinic.visits())||[]).filter((v:any)=>v.status==='IN_CONSULTATION'));}catch(e){Alert.alert('Diagnosis',errMsg(e));}},[]);useEffect(()=>{load();},[load]);const save=async()=>{if(!selected||!name)return Alert.alert('Diagnosis','Select a visit and enter diagnosis.');try{await clinic.diagnosis({visitId:selected.id,diagnosisName:name,notes});Alert.alert('Saved','Diagnosis saved successfully.');setName('');setNotes('');load();}catch(e){Alert.alert('Diagnosis',errMsg(e));}};return <Screen title="Diagnosis" subtitle="Enter diagnosis using the same server contract as the web client." onRefresh={load}><Card><Section title="Patient Queue" subtitle="Select a patient in consultation."/>{rows.map(v=><Pressable key={v.id} onPress={()=>setSelected(v)} style={[s.selectRow,selected?.id===v.id&&s.selected]}><View style={{flex:1}}><Text style={s.rowTitle}>{v.patient?.name}</Text><Text style={s.rowSub}>Visit #{v.id} • {v.complaint||'No complaint'}</Text></View><Badge>SELECT</Badge></Pressable>)}</Card>{selected&&<Card><Section title="Enter Diagnosis" subtitle={`Visit #${selected.id} • ${selected.patient?.name}`}/><Input label="Diagnosis" value={name} onChangeText={setName} placeholder="Flu & Cough"/><Input label="Clinical Notes" value={notes} onChangeText={setNotes} multiline placeholder="Rest and drink fluids"/><Button title="Save Diagnosis" onPress={save}/></Card>}</Screen>}

function Prescriptions({role}:P){const [rows,setRows]=useState<any[]>([]);const [meds,setMeds]=useState<any[]>([]);const [visitId,setVisitId]=useState('');const [medId,setMedId]=useState('');const [qty,setQty]=useState('1');const load=useCallback(async()=>{try{const [v,m]=await Promise.all([clinic.visits(),clinic.medicines()]);setRows(unwrap(v)||[]);setMeds(unwrap(m)||[]);}catch(e){Alert.alert('Prescriptions',errMsg(e));}},[]);useEffect(()=>{load();},[load]);const rx=rows.flatMap(v=>(v.prescriptions||[]).map((p:any)=>({...p,patient:v.patient,visit:v})));const create=async()=>{if(!visitId||!medId)return Alert.alert('Prescription','Choose visit and medicine.');try{await clinic.prescription({visitId:Number(visitId),medicineId:Number(medId),quantity:Number(qty)});Alert.alert('Saved','Prescription created.');setVisitId('');setMedId('');load();}catch(e){Alert.alert('Prescription',errMsg(e));}};return <Screen title={role==='PHARMACIST'?'Prescription Detail':'Prescriptions'} subtitle={role==='DOCTOR'?'Create and review medicine orders.':'Review incoming prescriptions and preparation status.'} onRefresh={load}>{role==='DOCTOR'&&<Card><Section title="Create Prescription"/><Text style={s.label}>Visit</Text><View style={s.chips}>{rows.filter(v=>v.status==='IN_CONSULTATION').map(v=><Pressable key={v.id} onPress={()=>setVisitId(String(v.id))} style={[s.chip,visitId===String(v.id)&&s.chipActive]}><Text style={[s.chipText,visitId===String(v.id)&&s.chipTextActive]}>{v.patient?.name} #{v.id}</Text></Pressable>)}</View><Text style={s.label}>Medicine</Text><View style={s.chips}>{meds.map(m=><Pressable key={m.id} onPress={()=>setMedId(String(m.id))} style={[s.chip,medId===String(m.id)&&s.chipActive]}><Text style={[s.chipText,medId===String(m.id)&&s.chipTextActive]}>{m.name} ({m.stock})</Text></Pressable>)}</View><Input label="Quantity" value={qty} onChangeText={setQty} keyboardType="numeric"/><Button title="Create Prescription" onPress={create}/></Card>}<Card><Section title="Prescription History" subtitle={`${rx.length} prescription records`}/>{rx.map(r=><View key={r.id} style={s.prescriptionRow}><View style={{flex:1}}><Text style={s.rowTitle}>{r.medicine?.name}</Text><Text style={s.rowSub}>{r.patient?.name} • Qty {r.quantity} • {r.medicine?.dosage}</Text></View><Badge tone={statusTone(r.status)}>{r.status}</Badge>{role==='PHARMACIST'&&r.status==='PENDING'&&<Pressable style={s.smallAction} onPress={async()=>{try{await clinic.prescriptionStatus(r.id,'READY');Alert.alert('Ready','Medicine marked ready.');load();}catch(e){Alert.alert('Pharmacy',errMsg(e));}}}><Text style={s.smallActionText}>READY</Text></Pressable>}</View>)}</Card>{!rx.length&&<Empty text="No prescriptions yet."/>}</Screen>}

function Notes({role}:P){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{clinic.visits().then(r=>setRows(unwrap(r)||[])).catch(()=>{});},[]);return <Screen title={role==='NURSE'?'Notes & Tasks':'Medical Notes'} subtitle="Review clinical notes and patient complaints."><Card><Section title="Clinical Notes"/>{rows.slice(0,10).map(v=><Row key={v.id} icon="document-text-outline" title={v.patient?.name||`Visit #${v.id}`} subtitle={v.complaint||'No complaint recorded.'} right={v.notes?<Badge tone="success">NOTES</Badge>:<Badge>EMPTY</Badge>}/>)}</Card><Card><Section title="Task List"/><Text style={s.muted}>• Review outstanding queue items</Text><Text style={s.muted}>• Confirm clinical notes</Text><Text style={s.muted}>• Keep patient flow moving</Text></Card></Screen>}
function Schedule({role}:P){const [rows,setRows]=useState<any[]>([]);const load=useCallback(async()=>{try{setRows(unwrap(await clinic.visits())||[]);}catch(e){Alert.alert('Schedule',errMsg(e));}},[]);useEffect(()=>{load();},[load]);return <Screen title={`${roleLabels[role]} Schedule`} subtitle="Today's outpatient schedule." onRefresh={load}><Card><Section title="Today's Schedule" subtitle="Outpatient appointments"/>{rows.map(v=><Row key={v.id} icon="calendar-outline" title={`${dateTime(v.visitDate)} • ${v.patient?.name}`} subtitle={`${v.doctor?.name} • ${v.complaint||'Routine visit'}`} right={<Badge tone={statusTone(v.status)}>{statusLabel(v.status)}</Badge>}/>)}</Card></Screen>}

function SearchPatients({role}:P){const [q,setQ]=useState('');const [rows,setRows]=useState<any[]>([]);const load=useCallback(async()=>{try{setRows(unwrap(await clinic.patients(q))||[]);}catch(e){Alert.alert('Search',errMsg(e));}},[q]);useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t);},[load]);return <Screen title="Patient Search" subtitle="Find a patient before initial assessment." onRefresh={load}><Input label="Search" value={q} onChangeText={setQ} placeholder="Name or phone"/><Card>{rows.map(p=><Row key={p.id} icon="search-outline" title={p.name} subtitle={`${p.phone} • ${p.age} years • ${p.gender}`}/>)}</Card>{!rows.length&&<Empty text="Patient not found."/>}</Screen>}
function PatientInfo({role}:P){const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const load=useCallback(async()=>{try{const r=unwrap(await clinic.visits())||[];setRows(r);if(!selected&&r[0])setSelected(r[0]);}catch(e){Alert.alert('Patient Info',errMsg(e));}},[selected]);useEffect(()=>{load();},[load]);return <Screen title="Patient Info & Vitals" subtitle="Patient demographics and latest examination." onRefresh={load}><Card><Section title="Visits"/>{rows.map(v=><Pressable key={v.id} onPress={()=>setSelected(v)} style={[s.selectRow,selected?.id===v.id&&s.selected]}><View style={{flex:1}}><Text style={s.rowTitle}>{v.patient?.name}</Text><Text style={s.rowSub}>Visit #{v.id} • {dateTime(v.visitDate)}</Text></View><Badge tone={statusTone(v.status)}>{statusLabel(v.status)}</Badge></Pressable>)}</Card>{selected&&<><Card><Section title="Patient Details"/><Info label="Name" value={selected.patient?.name}/><Info label="Gender" value={selected.patient?.gender}/><Info label="Age" value={selected.patient?.age}/><Info label="Phone" value={selected.patient?.phone}/><Info label="Address" value={selected.patient?.address}/></Card><Card><Section title="Vital Signs"/><Info label="Blood pressure" value={selected.bloodPressure||'—'}/><Info label="Temperature" value={selected.temperature!=null?`${selected.temperature} °C`:'—'}/><Info label="Weight" value={selected.weight!=null?`${selected.weight} kg`:'—'}/><Info label="Height" value={selected.height!=null?`${selected.height} cm`:'—'}/></Card></>}</Screen>}
function Info({label,value}:{label:string;value:any}){return <View style={s.info}><Text style={s.muted}>{label}</Text><Text style={s.infoValue}>{String(value??'—')}</Text></View>}
function Assessment({role}:P){const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [notes,setNotes]=useState('');const load=useCallback(async()=>{try{setRows((unwrap(await clinic.visits())||[]).filter((v:any)=>v.status==='WAITING'));}catch(e){Alert.alert('Assessment',errMsg(e));}},[]);useEffect(()=>{load();},[load]);const save=async()=>{if(!selected)return Alert.alert('Assessment','Select a waiting patient.');try{await clinic.vitals(selected.id,{notes});Alert.alert('Saved','Initial assessment saved and patient moved to consultation.');setSelected(null);setNotes('');load();}catch(e){Alert.alert('Assessment',errMsg(e));}};return <Screen title="Initial Assessment" subtitle="Record symptoms before the patient enters doctor consultation." onRefresh={load}><Card><Section title="Waiting Patients"/>{rows.map(v=><Pressable key={v.id} onPress={()=>setSelected(v)} style={[s.selectRow,selected?.id===v.id&&s.selected]}><View style={{flex:1}}><Text style={s.rowTitle}>{v.patient?.name}</Text><Text style={s.rowSub}>{v.complaint||'No complaint'} • {dateTime(v.visitDate)}</Text></View><Badge tone="warning">WAITING</Badge></Pressable>)}</Card>{selected&&<Card><Section title="Symptoms & Initial Assessment" subtitle={selected.patient?.name}/><Input label="Assessment notes" value={notes} onChangeText={setNotes} multiline placeholder="Symptoms, observations..."/><Button title="Save Assessment" onPress={save}/></Card>}</Screen>}
function Vitals({role}:P){const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [form,setForm]=useState({bloodPressure:'',temperature:'',weight:'',height:'',notes:''});const load=useCallback(async()=>{try{const r=unwrap(await clinic.visits())||[];setRows(r.filter((v:any)=>v.status==='WAITING'));}catch(e){Alert.alert('Vitals',errMsg(e));}},[]);useEffect(()=>{load();},[load]);const save=async()=>{if(!selected)return Alert.alert('Vitals','Select a waiting patient.');try{await clinic.vitals(selected.id,{bloodPressure:form.bloodPressure,temperature:Number(form.temperature)||undefined,weight:Number(form.weight)||undefined,height:Number(form.height)||undefined,notes:form.notes});Alert.alert('Saved','Vitals saved and visit moved to consultation.');setSelected(null);setForm({bloodPressure:'',temperature:'',weight:'',height:'',notes:''});load();}catch(e){Alert.alert('Vitals',errMsg(e));}};return <Screen title="Record Vitals" subtitle="Blood pressure, temperature, weight, height and notes." onRefresh={load}><Card><Section title="Waiting Patients"/>{rows.map(v=><Pressable key={v.id} onPress={()=>setSelected(v)} style={[s.selectRow,selected?.id===v.id&&s.selected]}><View style={{flex:1}}><Text style={s.rowTitle}>{v.patient?.name}</Text><Text style={s.rowSub}>Visit #{v.id} • {dateTime(v.visitDate)}</Text></View><Badge tone="warning">WAITING</Badge></Pressable>)}</Card>{selected&&<Card><Section title="Vital Signs" subtitle={selected.patient?.name}/><Input label="Blood pressure" value={form.bloodPressure} onChangeText={v=>setForm({...form,bloodPressure:v})} placeholder="120/80"/><View style={s.formRow}><View style={{flex:1}}><Input label="Temperature" value={form.temperature} onChangeText={v=>setForm({...form,temperature:v})} keyboardType="decimal-pad" placeholder="36.7"/></View><View style={{flex:1}}><Input label="Weight" value={form.weight} onChangeText={v=>setForm({...form,weight:v})} keyboardType="decimal-pad" placeholder="60"/></View></View><Input label="Height" value={form.height} onChangeText={v=>setForm({...form,height:v})} keyboardType="decimal-pad" placeholder="165"/><Input label="Notes" value={form.notes} onChangeText={v=>setForm({...form,notes:v})} multiline/><Button title="Save Vitals" onPress={save}/></Card>}</Screen>}
function Inventory({role}:P){const [rows,setRows]=useState<any[]>([]);const load=useCallback(async()=>{try{setRows(unwrap(await clinic.medicines())||[]);}catch(e){Alert.alert('Inventory',errMsg(e));}},[]);useEffect(()=>{load();},[load]);return <Screen title="Medicine Inventory" subtitle="Medicine name, dosage, stock and price." onRefresh={load}><Card>{rows.map(m=><Row key={m.id} icon="cube-outline" title={m.name} subtitle={`${m.dosage} • ${money(m.price)}`} right={<Badge tone={m.stock<20?'danger':'success'}>{m.stock} stock</Badge>}/>)}</Card>{!rows.length&&<Empty text="No medicine records."/>}</Screen>}
function Stock({role}:P){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{clinic.medicines().then(r=>setRows(unwrap(r)||[])).catch(()=>{});},[]);return <Screen title="Stock Management" subtitle="Monitor stock level before preparing prescriptions."><View style={s.grid}><Stat label="Medicines" value={rows.length} icon="cube-outline"/><Stat label="Low Stock" value={rows.filter(m=>m.stock<20).length} icon="warning-outline" tone="amber"/><Stat label="Total Units" value={rows.reduce((a,m)=>a+Number(m.stock||0),0)} icon="layers-outline" tone="green"/></View><Card><Section title="Inventory Overview"/>{rows.map(m=><Row key={m.id} title={m.name} subtitle={`${m.dosage} • ${money(m.price)}`} right={<Badge tone={m.stock<20?'danger':m.stock<50?'warning':'success'}>{m.stock}</Badge>}/>)}</Card></Screen>}
function Notifications({role}:P){const [meds,setMeds]=useState<any[]>([]);const [rx,setRx]=useState<any[]>([]);useEffect(()=>{Promise.all([clinic.medicines(),clinic.visits()]).then(([m,v])=>{setMeds(unwrap(m)||[]);setRx((unwrap(v)||[]).flatMap((x:any)=>(x.prescriptions||[]).map((p:any)=>({...p,patient:x.patient}))));}).catch(()=>{});},[]);return <Screen title="Notifications" subtitle="Workflow notifications for pharmacy operations."><Card><Section title="Notifications" subtitle="Today"/>{meds.filter(m=>m.stock<20).map(m=><Row key={`m${m.id}`} icon="warning-outline" title={`Low stock: ${m.name}`} subtitle={`${m.stock} units remaining`} right={<Badge tone="danger">ACTION</Badge>}/>)}{rx.filter(r=>r.status==='PENDING').map(r=><Row key={`r${r.id}`} icon="flask-outline" title={`Pending prescription: ${r.medicine?.name}`} subtitle={`${r.patient?.name||'Patient'} • Qty ${r.quantity}`} right={<Badge tone="warning">PENDING</Badge>}/>)}{!meds.some(m=>m.stock<20)&&!rx.some(r=>r.status==='PENDING')&&<Text style={s.muted}>No urgent notifications.</Text>}</Card></Screen>}
function History({role}:P){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{clinic.visits().then(r=>setRows(unwrap(r)||[])).catch(()=>{});},[]);return <Screen title="Visit History" subtitle="Patient self-service view."><Card>{rows.map(v=><Row key={v.id} icon="document-text-outline" title={`Visit #${v.id} • ${v.doctor?.name}`} subtitle={`${dateTime(v.visitDate)} • ${v.complaint||'No complaint'}`} right={<Badge tone={statusTone(v.status)}>{statusLabel(v.status)}</Badge>}/>)}</Card>{!rows.length&&<Empty text="No visit history yet."/>}</Screen>}

function dateTime(value:any){if(!value)return '—';return new Date(value).toLocaleString('id-ID',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});}

const s=StyleSheet.create({
  muted:{color:colors.muted,fontSize:12,lineHeight:19},
  grid:{flexDirection:'row',flexWrap:'wrap',gap:9,marginBottom:2},
  statIcon:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},
  statValue:{fontSize:24,fontWeight:'900',color:colors.navyDark,marginTop:7},
  row:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:15,padding:12,marginBottom:8,flexDirection:'row',alignItems:'center',gap:10},
  rowIcon:{width:40,height:40,borderRadius:12,backgroundColor:'#EAF2F3',alignItems:'center',justifyContent:'center'},
  rowTitle:{fontSize:13,fontWeight:'900',color:colors.navyDark},
  rowSub:{fontSize:10,color:colors.muted,marginTop:3,lineHeight:15},
  chev:{fontSize:22,color:colors.muted},
  empty:{alignItems:'center',gap:8,paddingVertical:12},
  darkKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#AEB7CA'},
  darkTitle:{fontSize:24,fontWeight:'900',color:colors.white,marginTop:5},
  darkText:{fontSize:12,lineHeight:19,color:'#D5DAE4',marginTop:5},
  bigMoney:{fontSize:30,fontWeight:'900',color:colors.navyDark,marginTop:2},
  smallBig:{fontSize:17,fontWeight:'900',color:colors.navyDark,marginTop:3},
  two:{flexDirection:'row',gap:20,marginTop:14},
  sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},
  queueItem:{borderTopWidth:1,borderTopColor:'#EEEAE2',paddingVertical:12,gap:7},
  smallAction:{alignSelf:'flex-start',backgroundColor:'#E8F2F6',borderRadius:10,paddingHorizontal:11,paddingVertical:8,marginTop:3},
  smallActionText:{fontSize:10,fontWeight:'900',color:colors.tealBright},
  formRow:{flexDirection:'row',gap:10},
  chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:10},
  chip:{borderWidth:1,borderColor:colors.border,borderRadius:11,paddingHorizontal:10,paddingVertical:9,backgroundColor:colors.white},
  chipActive:{backgroundColor:'#E8F2F6',borderColor:colors.tealBright},
  chipText:{fontSize:10,fontWeight:'900',color:colors.muted},
  chipTextActive:{color:colors.tealBright},
  label:{color:colors.navyDark,fontSize:11,fontWeight:'900',marginBottom:7},
  selectRow:{borderWidth:1,borderColor:colors.border,borderRadius:13,padding:12,marginBottom:8,flexDirection:'row',alignItems:'center',gap:9,backgroundColor:colors.white},
  selected:{borderColor:colors.tealBright,backgroundColor:'#F1F7F7'},
  prescriptionRow:{borderTopWidth:1,borderTopColor:'#EEEAE2',paddingVertical:12,gap:7},
  info:{flexDirection:'row',justifyContent:'space-between',paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#F0EEE8'},
  infoValue:{fontWeight:'900',color:colors.navyDark,maxWidth:'58%',textAlign:'right'},
  result:{marginTop:12,fontWeight:'900',fontSize:12},
  moneyGrid:{flexDirection:'row',gap:35,marginTop:15},
  chartRow:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:9},
  chartDate:{width:42,fontSize:10,color:colors.muted},
  barTrack:{flex:1,height:10,borderRadius:99,backgroundColor:'#EEF0F0',overflow:'hidden'},
  bar:{height:'100%',backgroundColor:colors.tealBright,borderRadius:99},
  chartValue:{width:24,textAlign:'right',fontSize:10,fontWeight:'900',color:colors.navyDark}
});
