import { useState, type PropsWithChildren } from 'react';
import { Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'expo-router';
import { colors } from '../constants/theme';
import { roleLabels, roleMenus } from '../constants/navigation';
import { useAuth } from '../context/AuthContext';
export default function RoleShell({children}: PropsWithChildren) { const {user,logout}=useAuth(); const router=useRouter(); const [open,setOpen]=useState(false); if(!user)return null; const menu=roleMenus[user.role]; const go=(key:string)=>{setOpen(false);if(key==='dashboard')router.replace(`/dashboard/${user.role.toLowerCase()}`);else router.push(`/dashboard/${user.role.toLowerCase()}/${key}`);}; return <View style={s.root}><SafeAreaView style={s.top}><View style={s.topInner}><Pressable onPress={()=>setOpen(true)} style={s.icon}><Ionicons name="menu-outline" size={23} color={colors.navyDark}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>ASSISTDOC</Text><Text style={s.role}>{roleLabels[user.role]} Workspace</Text></View><View style={s.avatar}><Text style={s.avatarText}>{user.name[0]?.toUpperCase()}</Text></View></View></SafeAreaView>{children}<Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><Pressable style={s.overlay} onPress={()=>setOpen(false)}><Pressable style={s.drawer} onPress={(e)=>e.stopPropagation()}><View style={s.brand}><View style={s.logo}><Text style={s.logoText}>+</Text></View><View><Text style={s.brandText}>AssistDoc</Text><Text style={s.small}>{roleLabels[user.role]} workspace</Text></View></View><ScrollView contentContainerStyle={{padding:14}}>{menu.map(item=><Pressable key={item.key} onPress={()=>go(item.key)} style={s.menu}><Ionicons name={item.icon as any} size={20} color={colors.tealBright}/><View style={{flex:1}}><Text style={s.menuText}>{item.label}</Text><Text style={s.menuDesc}>{item.description}</Text></View><Ionicons name="chevron-forward" size={16} color={colors.muted}/></Pressable>)}</ScrollView><View style={s.bottom}><Text style={s.user}>{user.name}</Text><Text style={s.email}>{user.email}</Text><Pressable onPress={()=>{setOpen(false);logout();}} style={s.logout}><Ionicons name="log-out-outline" size={18} color={colors.danger}/><Text style={{color:colors.danger,fontWeight:'900'}}>Logout</Text></Pressable></View></Pressable></Pressable></Modal></View>; }
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},top:{backgroundColor:'#FDFBF6',borderBottomWidth:1,borderBottomColor:colors.border},topInner:{height:64,flexDirection:'row',alignItems:'center',paddingHorizontal:14,gap:10},icon:{width:42,height:42,borderRadius:13,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:2,color:colors.tealBright},role:{fontSize:15,fontWeight:'900',color:colors.navyDark,marginTop:2},avatar:{width:38,height:38,borderRadius:19,backgroundColor:colors.cream,alignItems:'center',justifyContent:'center'},avatarText:{fontWeight:'900',color:colors.navyDark},overlay:{flex:1,backgroundColor:'rgba(16,26,61,.45)'},drawer:{width:'88%',maxWidth:390,backgroundColor:colors.background,flex:1,paddingTop:18},brand:{paddingHorizontal:18,paddingBottom:18,flexDirection:'row',gap:12,alignItems:'center',borderBottomWidth:1,borderBottomColor:colors.border},logo:{width:45,height:45,borderRadius:14,backgroundColor:colors.navyDark,alignItems:'center',justifyContent:'center'},logoText:{fontSize:30,fontWeight:'900',color:colors.tealBright},brandText:{fontSize:20,fontWeight:'900',color:colors.navyDark},small:{fontSize:9,fontWeight:'800',color:colors.muted,marginTop:2},menu:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:15,padding:12,marginBottom:8,flexDirection:'row',alignItems:'center',gap:11},menuText:{fontSize:13,fontWeight:'900',color:colors.navyDark},menuDesc:{fontSize:10,color:colors.muted,marginTop:2},bottom:{borderTopWidth:1,borderTopColor:colors.border,padding:16},user:{fontWeight:'900',color:colors.navyDark},email:{fontSize:11,color:colors.muted,marginTop:2},logout:{marginTop:12,flexDirection:'row',gap:8,alignItems:'center',paddingVertical:10}}
);
