import { PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { colors, radius } from '../constants/theme';
export function Card({ children, dark=false }: PropsWithChildren<{dark?:boolean}>) { return <View style={[s.card, dark && s.dark]}>{children}</View>; }
export function Button({ title, onPress, secondary=false, danger=false, loading=false, disabled=false }: {title:string;onPress:()=>void;secondary?:boolean;danger?:boolean;loading?:boolean;disabled?:boolean}) { return <Pressable disabled={disabled||loading} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,danger&&s.danger,(disabled||loading)&&{opacity:.55},pressed&&{opacity:.85}]}>{loading?<ActivityIndicator color={secondary?colors.teal:colors.white}/>:<Text style={[s.buttonText,secondary&&{color:colors.teal}]}>{title}</Text>}</Pressable>; }
export function Input({label, ...props}: {label:string}&TextInputProps) { return <View style={{marginBottom:13}}><Text style={s.label}>{label}</Text><TextInput {...props} placeholderTextColor="#9AA1AE" style={[s.input, props.multiline&&{height:100,textAlignVertical:'top',paddingTop:12}]} /></View>; }
export function Badge({children,tone='info'}: PropsWithChildren<{tone?:'info'|'success'|'warning'|'danger'}>) { const bg=tone==='success'?'#E8F5EF':tone==='warning'?'#FFF3DD':tone==='danger'?'#FBEAE7':'#E8F2F6'; const fg=tone==='success'?colors.success:tone==='warning'?colors.warning:tone==='danger'?colors.danger:colors.teal; return <View style={[s.badge,{backgroundColor:bg}]}><Text style={{color:fg,fontSize:10,fontWeight:'900'}}>{children}</Text></View>; }
export function Section({title,subtitle}: {title:string;subtitle?:string}) { return <View style={{marginBottom:12}}><Text style={s.section}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>; }
const s=StyleSheet.create({card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:16,marginBottom:14,shadowColor:'#000',shadowOpacity:.035,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:1},dark:{backgroundColor:colors.navyDark,borderColor:colors.navyDark},button:{minHeight:48,borderRadius:radius.md,backgroundColor:colors.tealBright,alignItems:'center',justifyContent:'center',paddingHorizontal:16,marginTop:7},secondary:{backgroundColor:'#EDF3F4',borderWidth:1,borderColor:'#D5E2E4'},danger:{backgroundColor:colors.danger},buttonText:{color:colors.white,fontSize:13,fontWeight:'900'},label:{color:colors.navyDark,fontSize:11,fontWeight:'900',marginBottom:6},input:{height:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.white,paddingHorizontal:13,color:colors.navyDark,fontSize:14},badge:{alignSelf:'flex-start',paddingHorizontal:9,paddingVertical:6,borderRadius:99},section:{color:colors.navyDark,fontSize:18,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:3}});

export const styles=s;
